version: '3'
services:
  airflow:
    build: .
    container_name: airflow
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow:/opt/airflow/src

    volumes:
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data

    command: bash -c "tail -f /dev/null" 

    # command: >
    #   bash -c "
    #   airflow db upgrade &&
    #   airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
    #   airflow webserver --port 8080 &
    #   airflow scheduler
    #   "